AWSTemplateFormatVersion: '2010-09-09'
Description: Convert EBS gp2 volumes to gp3 daily at 2 am US Eastern Time

Resources:
  ConvertEBSVolumesLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.handler
      Role: !GetAtt ConvertEBSVolumesLambdaRole.Arn
      FunctionName: ConvertEBSVolumesLambda
      Runtime: python3.8
      Timeout: 300
      Code:
        ZipFile: |
          import boto3
          import datetime

          def handler(event, context):
              ec2 = boto3.client('ec2')

              # Get all gp2 volumes
              response = ec2.describe_volumes(Filters=[{'Name': 'volume-type', 'Values': ['gp2']}])

              # Convert each gp2 volume to gp3
              for volume in response['Volumes']:
                  volume_id = volume['VolumeId']
                  print(f"Converting volume {volume_id} to gp3")
                  ec2.modify_volume(VolumeId=volume_id, VolumeType='gp3')

              print("Conversion completed successfully")

      Environment:
        Variables:
          TIMEZONE: 'America/New_York'  # Change to the appropriate timezone if needed

  ConvertEBSVolumesLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ConvertEBSVolumesLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeVolumes
                  - ec2:ModifyVolume
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'

  ConvertEBSVolumesEventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      ScheduleExpression: 'cron(0 6 * * ? *)'  # 2 am US Eastern Time (UTC-5)
      State: 'ENABLED'
      Targets:
        - Arn: !GetAtt ConvertEBSVolumesLambdaFunction.Arn
          Id: 'ConvertEBSVolumesLambdaTarget'

Outputs:
  LambdaFunctionArn:
    Description: 'ARN of the Lambda function'
    Value: !GetAtt ConvertEBSVolumesLambdaFunction.Arn
